### PR TITLE
WCT v8 + Labs Update

### PR DESCRIPTION
**Pull request by Arlodotexe**
The CommunityToolkit/Windows and CommunityToolkit/Labs-Windows repos have completed their migration to .NET 7. This PR submits a finished net7-based WASM build of the Toolkit Gallery to the https://toolkitlabs.dev/ website.

All available optimizations are enabled for this build, with 2 notable exceptions:
- AoT compilation is not enabled but can be explored now. Ran into several issues setting this up, but the toolkit is set up to quickly flip on the AoT profiler to generate the files needed.
- MultiThreading. Controls in the gallery don't make heavy use of background threads, so we've disabled this for now as it caused issues in Labs with Rive, and generally complicated the setup.

Overall, this build contains the new v8 Toolkit components, components from Labs, and has several optimizations which should speed up load times and general performance.

### CODE REVIEW

**Comment by michael-hawker** [comment]
I thought @Sergio0694 had opened an issue about some AoT stuff we had to do for the Toolkit, but can't find it now.

@Arlodotexe is there an accompanying tooling PR for showing the 'experimental' infobar?

What's the best way to preview these changes? Can I just pull this branch and use a local web host to view the page I guess?

**Comment by Sergio0694** [comment]
Happy to open a new issue if it can help for tracking! 🙂

**Comment by Arlodotexe** [comment]
> @Arlodotexe is there an accompanying tooling PR for showing the 'experimental' infobar?

This update is going out before @niels9001 has that ready to remedy the slowdowns reported by our users for the current net5 build.

The AoT issues were on the Uno Wasm side of things, see [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/de5c2491ce24ec62af83bdc95e41a35fd2237350/ProjectHeads/App.Head.Wasm.props#L9), no other platform is affected.

**Comment by Arlodotexe** [comment]
> Can I just pull this branch and use a local web host to view the page I guess?

Yep, running `dotnet serve` should do it

**Comment by michael-hawker** [comment]
Ah, for future people, `dotnet serve` is an additional tool, found here: https://github.com/natemcmaster/dotnet-serve

**Comment by michael-hawker** [comment]
@Arlodotexe just two, hopefully small. things:

1. Can you replace the rectangle 'X' icon with [the Labs icon](https://github.com/CommunityToolkit/design-assets/tree/main/Logos/Windows-Labs):

image

We should do this in the templates too. Anything new just gets the experimental 'Labs' icon as the placeholder until we bring it over and make a proper icon for whatever that thing is.

2. The Layouts icon is also missing:

image

_Follow-up WASM/Uno items for later_ - FYI @niels9001:
- Did we ever find out why Settings Expander's header content is blank?
- Segmented ignores horizontal alignment?

**Comment by Arlodotexe** [comment]
Related to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/151

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
